<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Makkuzz" name="SDETSelenium.Assignment1.HomePage" tests="6" failures="0" timestamp="2020-05-14T11:27:48 IST" time="75.957" errors="1">
  <testcase name="htmlContactFormNavigation" time="11.931" classname="SDETSelenium.Assignment1.HomePage"/>
  <system-out/>
  <testcase name="datepick" time="12.623" classname="SDETSelenium.Assignment1.HomePage"/>
  <system-out/>
  <testcase name="RentalCar" time="12.760" classname="SDETSelenium.Assignment1.HomePage">
    <error type="java.lang.IndexOutOfBoundsException" message="Index: 6, Size: 5">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 6, Size: 5
at java.util.ArrayList.rangeCheck(Unknown Source)
at java.util.ArrayList.get(Unknown Source)
at SDETSelenium.Assignment1.HomePage.RentalCar(HomePage.java:150)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
at org.testng.TestNG.runSuites(TestNG.java:1066)
at org.testng.TestNG.run(TestNG.java:1034)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- RentalCar -->
  <system-out/>
  <testcase name="dropable" time="13.703" classname="SDETSelenium.Assignment1.HomePage"/>
  <system-out/>
  <testcase name="selectablePageNavigation" time="12.692" classname="SDETSelenium.Assignment1.HomePage"/>
  <system-out/>
  <testcase name="selectMenu" time="12.248" classname="SDETSelenium.Assignment1.HomePage"/>
  <system-out/>
</testsuite> <!-- SDETSelenium.Assignment1.HomePage -->
